<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
/**
 * Operations
 */
$GLOBALS['TL_LANG']['tl_article']['header_articlewrapper'][0]		= 'New Wrapper';
$GLOBALS['TL_LANG']['tl_article']['header_articlewrapper'][1]		= 'Create a new wrapper';

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_article']['articlewrapper'][0]				= 'Enable article wrapper';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper'][1]				= 'Select here to make this article a wrapper element';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper']['articlewrapper_start']	= 'Wrapper start';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper']['articlewrapper_stop']	= 'Wrapper end';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper']['articlewrapper_single']= 'Single element';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper_style'][0]		= 'Layout';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper_style'][1]		= 'Choose a layout preset';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper_style']['fullwidth_contentboxed']		= 'fullwidth [content boxed]';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper_padding'][0]		= 'Padding top and bottom';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper_padding'][1]		= 'Add a padding to the top or bottom of the element.';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper_layout'][0]		= 'Layout-CSS';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper_layout'][1]		= 'Add a css class to the wrapper';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_article']['articlewrapper_legend']			= 'Article wrapper';
