<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Layout options labels
 */
$GLOBALS['TL_LANG']['pct_articlewrapper']['layout_options']['typ1']		= 'Typ 1';
$GLOBALS['TL_LANG']['pct_articlewrapper']['layout_options']['typ2']		= 'Typ 2';
$GLOBALS['TL_LANG']['pct_articlewrapper']['layout_options']['typ3']		= 'Typ 3';
$GLOBALS['TL_LANG']['pct_articlewrapper']['layout_options']['typ4']		= 'Typ 4';
$GLOBALS['TL_LANG']['pct_articlewrapper']['layout_options']['typ5']		= 'Typ 5';
$GLOBALS['TL_LANG']['pct_articlewrapper']['layout_options']['typ5']		= 'Typ 6';