<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
/**
 * Operations
 */
$GLOBALS['TL_LANG']['tl_article']['header_articlewrapper'][0]		= 'Neuer Wrapper';
$GLOBALS['TL_LANG']['tl_article']['header_articlewrapper'][1]		= 'Wählen Sie hier um einen neuen Artikel-Wrapper einzufügen.';

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_article']['articlewrapper'][0]				= 'Artikelwrapper aktivieren';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper'][1]				= 'Wählen Sie hier um den Artikel als Arikelumschlag zu verwenden.';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper']['articlewrapper_start']	= 'Umschlaganfang';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper']['articlewrapper_stop']	= 'Umschlagende';

$GLOBALS['TL_LANG']['tl_article']['articlewrapper_style'][0]		= 'Darstellungsart';
$GLOBALS['TL_LANG']['tl_article']['articlewrapper_style'][1]		= 'Wählen Sie die Darstellungsart.';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_article']['articlewrapper_legend']			= 'Artikelwrapper';
